#!bin/bash

as3:
	haxe build-as3.hxml

#build swf from generated AS3 and launch with adl
MAIN.swf : as3_src/__main__.as MAIN-App.xml	as3
	amxmlc -o MAIN.swf as3_src/__main__.as
	adl MAIN-App.xml
	#use command below if assets required
	#amxmlc -library-path+=assets/MAIN.swc -o MAIN.swf as3_src/__main__.as

#package the air app
app: MAIN.swf MAIN-App.xml 
	adt -package -storetype pkcs12 -keystore ${HOME}/flash/cert/cert.p12 -storepass belikemike MAIN.air MAIN-App.xml MAIN.swf assets icons

#package the android app
apk: MAIN.swf MAIN-App.xml 
	adt -package -target apk -storetype pkcs12 -keystore ${HOME}/flash/cert/cert.p12 -storepass belikemike MAIN.apk MAIN-App.xml MAIN.swf assets icons
