#! /bin/bash

DOCPATH="${HOME}/flexdocs/flex3_documentation/langref"
pushd $DOCPATH
FILEPATH="langref\/flash"
TAGS_FILE="${HOME}/.vim/tags/flash/tags"
TAGS_FILE_UNSORTED="${HOME}/.vim/tags/flash/tags_unsorted"

genDirTags()
{
#using global vars for now
#properties
egrep -o '<td class="summaryTableSignatureCol">\s*<a[^>]*>[^<]*</a>[^<]*<a[^>]*>[^<]*</a>' ${CLASS}.html | \
sed "s/<td class=\"summaryTableSignatureCol\">\s*<a[^>]*>\([^<]*\)<\/a>[^<]*<a[^>]*>\([^<]*\)<\/a>/\1	${FILEPATH}\/${PACKAGE}\/${CLASS}.as	\/^	public var \1:\2;$\/;\"	v/g" >> $TAGS_FILE_UNSORTED
#methods - includes constructors as functions
grep -o '<td class="summaryTableSignatureCol">\s*<div class="summarySignature">\s*<a[^>]*>[^<]*</a>([^)]*)' ${CLASS}.html | \
sed "s/<td class=\"summaryTableSignatureCol\">\s*<div class=\"summarySignature\">\s*<a[^>]*>\([^<]*\)<\/a>\(([^)]*)\)/\1	${FILEPATH}\/${PACKAGE}\/${CLASS}.as	\/^public function \1\2$\/;\"	f/g" | sed 's/<[^>]*>//g' >> $TAGS_FILE_UNSORTED
#AIR methods require a different regex as they have the air icon image
grep -o '<td class="summaryTableSignatureCol">\s*<div class="summarySignature"><img[^>]*>&nbsp;<a[^>]*>[^<]*</a>([^)]*)' ${CLASS}.html | \
sed "s/<td class=\"summaryTableSignatureCol\">\s*<div class=\"summarySignature\"><img[^>]*>&nbsp;<a[^>]*>\([^<]*\)<\/a>\(([^)]*)\)/\1	${FILEPATH}\/${PACKAGE}\/${CLASS}.as	\/^public function \1\2$\/;\"	f/g" | sed 's/<[^>]*>//g' | sed 's/&nbsp;//g' >> $TAGS_FILE_UNSORTED

}

#create empty file
cat "" > $TAGS_FILE_UNSORTED

for PACKAGE in `ls flash`
do
	if [ -d flash/$PACKAGE ]; then
	pushd flash/$PACKAGE
	for CLASS in `ls *.html | sed 's/.html//g'`
	do
		echo $CLASS
		genDirTags
	done
	popd
	fi
done
#add charts
pushd mx/charts
for CLASS in `ls *.html | sed 's/.html//g'`
do
	echo $CLASS
	genDirTags
done
popd
#subdirs
for PACKAGE in `ls mx/charts`
do
	if [ -d mx/charts/$PACKAGE ]; then
	pushd mx/charts/$PACKAGE
	for CLASS in `ls *.html | sed 's/.html//g'`
	do
		echo $CLASS
		genDirTags
	done
	popd
	fi
done

#add toplevel classes
FILEPATH="langref"
PACKAGE="Top Level"
for CLASS in Array Boolean Number Object String Vector XML XMLList
do
#properties
egrep -o '<td class="summaryTableSignatureCol">\s*<a[^>]*>[^<]*</a>[^<]*<a[^>]*>[^<]*</a>' ${CLASS}.html | \
sed "s/<td class=\"summaryTableSignatureCol\">\s*<a[^>]*>\([^<]*\)<\/a>[^<]*<a[^>]*>\([^<]*\)<\/a>/\1	${FILEPATH}\/${PACKAGE}\/${CLASS}.as	\/^	public var \1:\2;$\/;\"	v/g" >> $TAGS_FILE_UNSORTED
#methods - includes constructors as functions
grep -o '<td class="summaryTableSignatureCol">\s*<div class="summarySignature">\s*<a[^>]*>[^<]*</a>([^)]*)' ${CLASS}.html | \
sed "s/<td class=\"summaryTableSignatureCol\">\s*<div class=\"summarySignature\">\s*<a[^>]*>\([^<]*\)<\/a>\(([^)]*)\)/\1	${FILEPATH}\/${PACKAGE}\/${CLASS}.as	\/^public function \1\2$\/;\"f/g" | sed 's/<[^>]*>//g' >> $TAGS_FILE_UNSORTED
done
#write file header 
echo '!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/' > $TAGS_FILE
echo '!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/' >> $TAGS_FILE
echo '!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/' >> $TAGS_FILE
echo '!_TAG_PROGRAM_NAME	Exuberant C$TAGS_FILE	//' >> $TAGS_FILE
echo '!_TAG_PROGRAM_URL	http://c$TAGS_FILE.sourceforge.net	/official site/' >> $TAGS_FILE
echo '!_TAG_PROGRAM_VERSION	5.7	//' >> $TAGS_FILE
#sort
cat $TAGS_FILE_UNSORTED | sort >> $TAGS_FILE
rm $TAGS_FILE_UNSORTED
popd
#note - need to sort tags in vim w/ :%sort

